### ISSUE TITLE
Ghidra fails to create extremely large TerminatedCStrings

### ISSUE THREAD

**Issue by escape209** [astrelsky/ghidra_mdebug#9]
The ELF I am using contains some extremely large **(~35.5K characters)** strings, all for the same type, CGtV4d. The reason behind the huge size is the 256 overload definitions for the function CGtV4d::Set. 

Ghidra fails to create extremely large strings, probably length >=32768. As a result, .mdebug analysis fails. A workaround to this is to instead create a char[] for the same strings, as this type doesn't have the same limitation.

`Could not create DataType TerminatedCString
ghidra.program.model.util.CodeUnitInsertionException: Could not create DataType TerminatedCString
	at ghidra.program.model.data.DataUtilities.createData(DataUtilities.java:176)
	at mdebug.analysis.MdebugAnalyzer.createData(MdebugAnalyzer.java:309)
	at mdebug.analysis.MdebugAnalyzer.createStringTable(MdebugAnalyzer.java:329)
	at mdebug.analysis.MdebugAnalyzer.added(MdebugAnalyzer.java:103)
	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by astrelsky** [comment]
It should work if the size is explicitly set when creating the string. This occurs if you try to create it in the listing at the start of the string but it will be successfully created if you create it with all the characters highlighted.

**Comment by escape209** [comment]
Thanks, this does also work for creating the string manually. It doesn't allow the .mdebug analysis to complete, though, since the extension itself will always try to create a TerminatedCString for it, even if a string has already been made (Analysis -> One Shot -> MDEBUG).
